### ISSUE TITLE
In branch scarthgap systemd build got an error

### ISSUE THREAD

**Issue by Cherish-Gww** [JeffyCN/meta-rockchip#105]
I am using poky branch scarthgap, and I tested remove this patch will fix it.

https://github.com/JeffyCN/meta-rockchip/blob/b6b01a575a618cf8b06c359881f666782db6c5e8/recipes-core/systemd/systemd_%25.bbappend#L7

**Comment by JeffyCN** [comment]
thanks, should be fixed now

**Comment by asac** [comment]
I can confirm that scarthgap builds now with systemd.

**Comment by JeffyCN** [comment]
thanks for testing :)
