### ISSUE TITLE
Conflict with linux-firmware definition in poky branch is scarthgap

### ISSUE THREAD

**Issue by Cherish-Gww** [JeffyCN/meta-rockchip#106]
I tested delete L24-28 will be pass building. 
https://github.com/JeffyCN/meta-rockchip/blob/b6b01a575a618cf8b06c359881f666782db6c5e8/recipes-kernel/linux-firmware/linux-firmware_%25.bbappend#L24

**Comment by JeffyCN** [comment]
thanks, should be fixed now

**Comment by Cherish-Gww** [comment]
> thanks, should be fixed now

@JeffyCN 您是rockchip的工程师吗？

**Comment by JeffyCN** [comment]
> > thanks, should be fixed now
> 
> @JeffyCN 您是rockchip的工程师吗？ Rockchip未来会对yocto支持的力度有多少？

Yes.

The support level is similar to what it is now(IOW, just me😂).

This layer mainly provides common BSP packages and adaptation of chromium+weston/x11+gstreamer.
