### ISSUE TITLE
gstreamer playback x264

### ISSUE THREAD

**Issue by nandra** [JeffyCN/meta-rockchip#112]
Hello, I have x264 playback working using gstreamer1.0-libav library but it's SW only and took 130% CPU. Can I somehow enable HW decoding for x264 videos please? I'm using  RK3566. Thanks.

**Comment by JeffyCN** [comment]
The sugguested flow would be:
gstreamer-rockchip(mppvideodec) -> rockchip-mpp(librockchip_mpp.so) -> Rockchip BSP kernel's mpp driver.

Normally those things should be ready by default in the SDK, you can just run: gst-play-1.0 <video>
