### ISSUE TITLE
Glibc:do_configure fails due to old kernel headers

### ISSUE THREAD

**Issue by AlphaGX** [JeffyCN/meta-rockchip#113]
From a fresh install (cloned poky, meta-oe, meta-rockchip) glibc.bb do_configure step fails.

Reproduce setup:
```
mkdir yocto
cd yocto
git clone -b scarthgap git://git.yoctoproject.org/poky
git clone -b scarthgap git://git.openembedded.org/meta-openembedded.git
git clone -b scarthgap https://github.com/JeffyCN/meta-rockchip

source poky/oe-init-build-env
echo 'INHERIT += "rm_work"' >> conf/local.conf
bitbake-layers add-layer ../meta-openembedded/meta-oe/
bitbake-layers add-layer ../meta-rockchip/
MACHINE="rockchip-rk3328-evb" bitbake glibc
```

Relevant part of the error message:
```
| checking installed Linux kernel header files... 3.2.0 or later
| checking for kernel header at least 5.15... too old!
| configure: error: *** The available kernel headers are older than the requested
| *** compatible kernel version
```
Full log: https://pastebin.com/NyVxfXqi
Command: `MACHINE="rockchip-rk3328-evb" bitbake glibc 2>&1 > glibc.log`

My setup:
WSL2 debian
uname -a: `Linux A300 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux`

**Comment by JeffyCN** [comment]
i thought it should be fixed in https://github.com/JeffyCN/meta-rockchip/commit/51d2ccfb9d5aeb04a296982702e277e4209e0d0f

**Comment by AlphaGX** [comment]
I don't know  what to say really, I am using the latest commits so It shouldn't be an issue...
Should I roll back to the commit you mentioned ??

**Comment by JeffyCN** [comment]
Or modify there:
pokymeta/conf/bitbake.conf:470:OLDEST_KERNEL = "5.15

**Comment by JeffyCN** [comment]
closing this since i cannot repro it.
