### ISSUE TITLE
rk3588, chromium 122 video HW acceleration with Scarthgap and Kernel 6.1

### ISSUE THREAD

**Issue by chrisiberg** [JeffyCN/meta-rockchip#115]
Should this work since [v4l-rkmpp: Bump to 1.7.1]
did someone try it?

**Comment by chrisiberg** [comment]
Scarthgap needs at least kernel 5.15 for glibc_2.39, so I can't try it with the 5.10 and with 6.1 Kernel Video HW-acceleration does not work.
@JeffyCN Do you see any reason why this would not work with Scarthgap and Kernel 6.1?

**Comment by JeffyCN** [comment]
it doesn't require 5.15, it's configuable.

it works well on my board with my buildroot sdk + yocto chromium.

but i am not allowed go provide newer kernel code and some other codes, so i'm not sure would other parts affect it.

**Comment by JeffyCN** [comment]
maybe you can provide your rootfs image, i might try to test it with my internal 6.1 kernel to figure out which part went wrong. and maybe you can try to find other newer bsp kernel 6.1 code on other repo(for example radxa)

**Comment by chrisiberg** [comment]
That would be great!
To be clear, in chrome://gpu everything looks right, but if I inspect the video with STRG+SHIFT+I > More Tools > Media
Decoder name: VpxVideoDecoder or sometimes FFmpeg
Hardware decoder: **flase**
and CPU usage of chrome is much higher than with kirkstone and kernel 5.10

This is the Kernel source I used, because my hardware is a NanoPC-T6
https://github.com/friendlyarm/kernel-rockchip/tree/nanopi6-v6.1.y

**Comment by JeffyCN** [comment]
i cannot access that rootfs.img, no permission

**Comment by chrisiberg** [comment]
sorry, should work now.

**Comment by JeffyCN** [comment]
please try to upgrade the mpp :)

**Comment by chrisiberg** [comment]
Thnx a lot, I will try!

the changes from WORKDIR > UNPACKDIR does not work in all cases I had to change it in 
xserver-xorg for modesetting.conf and in
udev-conf-rocchip for 99-rockchip-permissions.rules

maybe you have a look at it.

**Comment by chrisiberg** [comment]
mpp upgrade does not make a difference 
![image](https://github.com/JeffyCN/meta-rockchip/assets/108681558/b1828e7c-cfa2-4b8c-ad0f-40b9dddb81aa)

**Comment by JeffyCN** [comment]
1/ Not sure about UNPACKDIR error, it's required by the newest poky, and it works well on my side. Please check your poky version

2/ It works with your image on my board after upgraded mpp and libmali.
That is because the meta-rockchip's kernel is old(and i'm not allowed to upgrade it). If your are using a new kernel, you can need to choose a matched mpp and libmali(valhall-g610-g13p0 for newest kernel)

**Comment by chrisiberg** [comment]
Thnx a lot Jeffy!
I got it, this is working!
