### ISSUE TITLE
EGL issue with weston on scarthgap branch

### ISSUE THREAD

**Issue by dylad** [JeffyCN/meta-rockchip#119]
Hello,

I am having some issues with EGL.
When building core-image-weston with meta-rockchip (scarthgap) for RK3588S board, examples app from weston using EGL crash with a segfault.  (for instance weston-simple-egl)

I am using lastest revision from scarthgap with poky and meta-openembedded. No others layers are involved.
I just add `DEPENDS:append:pn-xwayland = " libtirpc"` in my local.conf because xwayland seems to have a missing dependency.

I am building an image for RK3588S chip.

**Comment by JeffyCN** [comment]
maybe try to apply this:
https://github.com/JeffyCN/rockchip_mirrors/blob/buildroot/package/wayland/0003-client-Assign-proxy-to-default-queue-when-releasing-.patch

**Comment by dylad** [comment]
I didn't try the manifest but the first patch seems to work on my side !
Thanks @JeffyCN !

**Comment by dylad** [comment]
Hi again @JeffyCN 
While the segfault no longer happen, I just notice that weston-simple-egl produces two windows (see following screenshot):

![wayland-screenshot-2024-02-27_18-43-53](https://github.com/user-attachments/assets/8a1248d5-ddd3-4c79-9504-cd960102650f)

Then if I hit a Ctrl-C with a keyboard on Weston (not in the shell which started the app obviously), the second window is killed.

![wayland-screenshot-2024-02-27_18-44-07](https://github.com/user-attachments/assets/59f58849-019b-4af1-ac08-0f5a090f9a1f)

**Comment by JeffyCN** [comment]
it works well on my side, maybe try to upload your rootfs.img

**Comment by dylad** [comment]
I've started a fresh build, using the manifest this time. I'll see if there is a difference.
Are you also using a Rk3588S-based board ?

**Comment by dylad** [comment]
@JeffyCN 
In the mean time, you can find my generated rootfs [here](https://we.tl/t-q8Zl0c3y1H)

**Comment by JeffyCN** [comment]
didn't repro it with your rootfs, everything works well on my board...

**Comment by dylad** [comment]
It seems I mismatch my rootfs when flashing. Sorry about that.
I'll try to trigger this in a reproducible way on my side and come back to you.
Thanks for your help !

**Comment by dylad** [comment]
BTW, I just flashed a fresh image using scarthgap manifest file without the patch you mentioned from Buildroot.
weston-simple-egl segfaults again so I guess this patch is needed using Yocto build.
