### ISSUE TITLE
EDID with wrong checksum problem

### ISSUE THREAD

**Issue by chrisiberg** [JeffyCN/meta-rockchip#126]
When using an RK3588 or RK3568 in combination with a Novastar LED controller, I consistently encounter issues with the resolution settings.
It appears that Novastar is generating the necessary custom EDID with an incorrect checksum (based on what I’ve been able to reproduce so far), and Rockchip then overwrites this EDID with its own, which is not suitable for the correct resolution.

Does anybody have an idea to ignore the checksum with a setting or patch?

**Comment by JeffyCN** [comment]
don't know much about it, maybe try to revert https://patchwork.kernel.org/project/dri-devel/patch/eb493446e5a7fd442f78078dc49d83c6e458caa0.1649322799.git.jani.nikula@intel.com/
