### ISSUE TITLE
bitbake passes, but when I add "INHERIT:append = " rockchip-image" I get QA errors

### ISSUE THREAD

**Issue by wabushi** [JeffyCN/meta-rockchip#127]
**Please disregard previous edits, I was asking about a different repo with the same name**

I successfully bitbaked images for rockchip-rk3566-evb. I added INHERIT:append = " rockchip-image" to local.conf in order to have update.img and .wic file to load to my board (roc-rk3566-pc).
System is booting but stuck on "Rockchip Kernel" screen. I changed the RK_WIFIBT_RRECOMMENDS to fit the wireless module on the board. but it hasn't affected the problem.

My Main configurations are:
KBUILD_DEFCONFIG ?= "rockchip_linux_defconfig"
KERNEL_DEVICETREE = "rockchip/rk3566-evb2-lp4x-v10-linux.dtb"
UBOOT_MACHINE = "rk3568_defconfig"

Are they correct? What am I doing wrong?

**Comment by JeffyCN** [comment]
that means your kernel doesn't match the hardware, please ask your board's provider to get the correct workable kernel, and follow the readme to use it
