### ISSUE TITLE
Could you please rebase for chromium 130.0.6723.91

### ISSUE THREAD

**Issue by MastaG** [JeffyCN/meta-rockchip#130]
The patches do apply with fuzz, but compilation seems to fail.
If you have some spare time, could you please create a patch-set for chromium 130.0.6723.91.

**Comment by MastaG** [comment]
This is the error I'm getting:
```
../../media/gpu/v4l2/legacy/v4l2_video_decoder_backend_stateful.cc:446:20: error: non-constant-expression cannot be narrowed from type '__suseconds64_t' (aka 'long long') to 'long' in initializer list [-Wc++11-narrowing]
  446 |         .tv_nsec = timeval.tv_usec * 1000,
      |                    ^~~~~~~~~~~~~~~~~~~~~~
../../media/gpu/v4l2/legacy/v4l2_video_decoder_backend_stateful.cc:446:20: note: insert an explicit cast to silence this issue
  446 |         .tv_nsec = timeval.tv_usec * 1000,
      |                    ^~~~~~~~~~~~~~~~~~~~~~
      |                    static_cast<long>(    )
1 error generated.
```

**Comment by JeffyCN** [comment]
maybe try to add 'static_cast<long>' as it suggested:
```
-        .tv_nsec = timeval.tv_usec * 1000,
+        .tv_nsec = static_cast<long>(timeval.tv_usec * 1000),
```
guessing you are compiling for arm32, maybe these kind of errors would be better to be fixed in the official meta-browser?

**Comment by MastaG** [comment]
Hi @JeffyCN thanks for rebasing against Chromium 1.30 and sorry the compilation error,  I didn't check carefully whether it was part of your patchset.
Yes I'm building for armv7 (32bit) and I've applied the patch:
```
--- a/media/gpu/v4l2/legacy/v4l2_video_decoder_backend_stateful.cc    2024-11-08 16:10:21.678274282 +0100
+++ b/media/gpu/v4l2/legacy/v4l2_video_decoder_backend_stateful.cc    2024-11-08 16:12:03.583093122 +0100
@@ -443,7 +443,7 @@
     const struct timeval timeval = buffer->GetTimeStamp();
     const struct timespec timespec = {
         .tv_sec = timeval.tv_sec,
-        .tv_nsec = timeval.tv_usec * 1000,
+        .tv_nsec = static_cast<long>(timeval.tv_usec * 1000),
     };
 
     const int64_t flat_timespec =
```
It now builds and runs fine.

I'm running chromium with `--use-gl=angle --use-angle=gles-egl --use-cmd-decoder=passthrough` but when it runs it will print:
`ERROR:gl_display.cc(497)] EGL Driver message (Error) eglCreateContext: Requested version is not supported`

Also when I'm playing video, e.g. Netflix or YouTube, it will constantly print:
```
ERROR:gpu_channel.cc(503)] Buffer Handle is null.
ERROR:shared_image_interface_proxy.cc(134)] Buffer handle is null. Not creating a mailbox from it.
ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=SCANOUT_CPU_READ_WRITE
```

I'm running using the wayland platform.

Any ideas?

**Comment by MastaG** [comment]
Workaround for `Cannot create bo with format= YUV_420_BIPLANAR and usage=SCANOUT_CPU_READ_WRITE` spamming the logs is worked around by launching with `--disable-gpu-memory-buffer-video-frames`.
Fix should land in version 131.

The only bug remaining would be:  `ERROR:gl_display.cc(497)] EGL Driver message (Error) eglCreateContext: Requested version is not supported`

**Comment by MastaG** [comment]
I figured everything out :)
