### ISSUE TITLE
chromium 130: AV1 is not enabled

### ISSUE THREAD

**Issue by amazingfate** [JeffyCN/meta-rockchip#131]
The patch is found in v126: https://github.com/JeffyCN/meta-rockchip/blob/master/dynamic-layers/recipes-browser/chromium/chromium_126.0.6478/0001-HACK-media-Support-V4L2-video-decoder.patch#L651-L662, but missing in 130.

I get
```
[3725:3810:1116/000802.189424:VERBOSE1:v4l2_video_decoder_backend_stateful.cc(113)] Initialize(): Unsupported profile av1 profile main
```
when decoding av1 videos.

**Comment by JeffyCN** [comment]
done
