### ISSUE TITLE
Kirkstone update breakage

### ISSUE THREAD

**Issue by mrybczyn** [JeffyCN/meta-rockchip#26]
The layer breaks at kirkstone update that bumps xserver.   See the discussion at https://lists.openembedded.org/g/openembedded-core/message/168793

The change is expected to land in https://git.openembedded.org/openembedded-core/log/?h=kirkstone in the next hours

**Comment by JeffyCN** [comment]
thanks for noticing, 21.1.4_2022_07_29 uploaded
