### ISSUE TITLE
Missing driver for Xorg modesetting with rk3568

### ISSUE THREAD

**Issue by landai-n** [JeffyCN/meta-rockchip#27]
Branch: dunfell

Building the core-image-x11 for rk3568, the Xorg server fails to start. It seems that there is no driver for modesetting in the meta-rockchip layer. I found only a fbdev driver. It seems strange as the layer provide a conf file for Xorg that specifies that the default driver should be modesetting.

**Comment by JeffyCN** [comment]
please check the manifest repo
