### ISSUE TITLE
USB not working in JWS3288-I

### ISSUE THREAD

**Issue by hi3520** [JeffyCN/meta-rockchip#35]
Hi JeffyCN,

I am working on JWS3288-I industry evaluation board, i used your meta-rockchip layer and successful booted the target thank you.

When i insert usb stick in target there is no sign of usb i think proper dtb file should have use, currently i am using rk3288-evb-rk808.dtb, could you please suggest me proper dtb file for JWS3288.

I need to inform you that I don't have schematic or SDK for JWS3288

You can find the based details of JWS3288 from the following link https://www.icp-deutschland.de/en/industrial-pc/cpu-boards-cpu-cards/embedded-boards/3-5-inch-wafer/wafer-jws3288-i-2r16s-l44.html

**Comment by JeffyCN** [comment]
Hi,
sorry, i mostly working on user space these years. for kernel related issues, please contact the board vendor...

usb function likely related to kernel config and dts, it's kind of impossible for me(or anyone) to provide those for a random board.
(you can try to use your original prebuilt kernel image(boot.img/zboot.img) though)
