### ISSUE TITLE
xserver-xorg  branch rewrites breaks meta-rockchip releases

### ISSUE THREAD

**Issue by ydirson** [JeffyCN/meta-rockchip#4]
Branch 1.20.4 was rewritten, which makes eg. 1.20.4_2019_9_29 unreachable from the branch.
As a consequence, xserver-xorg recipe in release 1.1.0 fail to fetch, unless the download has been previously cached.

I guess the clean way to handle this is to ship patches in meta-rockchip, rather than pointing to a moving source tree.

**Comment by JeffyCN** [comment]
release tag is _not_ a moving source tree, and handling 30+ patches for every versions is unacceptable.

the clean way is to set src_uri to the tarball of that release tag(e.g. https://github.com/JeffyCN/xorg-xserver/archive/1.20.4_2019_9_26.tar.gz), but that would require to specify each tarball's checksum.

replace the branch with "nobranch=1" should be fine too.
