### ISSUE TITLE
Hide kernel logo?

### ISSUE THREAD

**Issue by tmm1** [JeffyCN/meta-rockchip#44]
Over HDMI I see "rockchip kernel" logo. I want to see the kernel log instead.

I tried `logo.nologo console=tty1` in cmdline,  but I couldn't make it work.

Is there another way?

**Comment by JeffyCN** [comment]
i mostly focus on user space.

for kernel logo, maybe try to disable it in the kernel dts, or maybe in the u-boot(i've heard that the kernel is reusing u-boot logo)
