### ISSUE TITLE
Question: rk3588 evb1 where to buy

### ISSUE THREAD

**Issue by nandra** [JeffyCN/meta-rockchip#47]
Hi,

I'm planning to do some experiments with rk3588 and this layer seems to support rk3588 evb1, but I cannot find any exact link on internet where to get it. Any idea where to get it pls? Thanks.

**Comment by JeffyCN** [comment]
try to contact the customer service:
https://www.rock-chips.com/a/en/contact/index.html

service@rock-chips.com
