### ISSUE TITLE
GBM application failed with error EGL_BAD_DISPLAY

### ISSUE THREAD

**Issue by namtrino** [JeffyCN/meta-rockchip#49]
I test ozone-gbm on rk3566 but it failed with error below.
```
[ERROR:gl_surface_egl.cc(1382)] eglInitialize Default failed with error EGL_BAD_DISPLAY
[ERROR:gl_ozone_egl.cc(20)] GLSurfaceEGL::InitializeOneOff failed.
[ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
```
But kmscube and glmark2-es2-drm work ok.

Is this a gbm driver issue?

**Comment by JeffyCN** [comment]
??? the yocto sdk with chromium worked well for years...

**Comment by JeffyCN** [comment]
i was using this to build images:
https://github.com/JeffyCN/yocto-manifests

**Comment by namtrino** [comment]
The Chromium Wayland from https://github.com/JeffyCN/yocto-manifests can run.
But I was faced with two issues, poor video playback performance and it crashed randomly.

**Comment by JeffyCN** [comment]
video playback is at the best performance, it has hw dec and dma importing and gpu rendering.

crash issue should related to chromium-wayland or chromium framework, you can report to chromium issue system.

chromium-x11 should work too.

gbm should be used in chromiumos, it requires more patches.

fydeos has chromiumos-like sdk for rk3399 and rk3588.

**Comment by JeffyCN** [comment]
one guess would be using egl get platform display api to get egl gbm display, instead of the legacy egl get display api

**Comment by namtrino** [comment]
Hi, chromium gbm require EGL version 1.5 (current version is  1.4) . Is it possible to upload version 1.5 to public?

**Comment by JeffyCN** [comment]
it's almost impossible to upgrade it.

and i don't think it requires that, because the google do have chromebook with chromeos(chrome + gbm) for 3288 and 3399, and fydeos has chromiumos(chromium + gbm) for 3399/3588.

**Comment by namtrino** [comment]
I already tested with RK3399 with [yocto-manifest](https://github.com/JeffyCN/yocto-manifests).
It also failed EGL_BAD_DISPLAY.

**Comment by JeffyCN** [comment]
it's been tested by lots of people for years...

**Comment by JeffyCN** [comment]
FYI, i've heard they use mali with dummy platform + google's minigbm for chrome os/chromium os's ozone gbm

**Comment by namtrino** [comment]
Thank you for an information. I think I should study FydeOS with rockchip platform first.
Because look like they use mpp (https://github.com/openFyde/overlay-rock5b-openfyde/blob/main/sys-kernel/chromeos-kernel-5_10/files/012-add-virtual-v4l2-devices.patch).

BTW, I will closed this issue because meta-rockchip focus on wayland with linux gbm.
