### ISSUE TITLE
Question aboud device support

### ISSUE THREAD

**Issue by l1m0nguy** [JeffyCN/meta-rockchip#5]
Hello.
Sorry for my question, but I haven't noticed anywhere. 
Is RK3399 supported?

**Comment by JeffyCN** [comment]
Only support rk3399 sapphire excavator board, check this manifest:
https://github.com/JeffyCN/yocto-manifests/blob/dunfell/rockchip-rk3399-sapphire-excavator.xml

Also check these README for how to build a demo version:
https://github.com/JeffyCN/mirrors
https://github.com/JeffyCN/yocto-manifests

**Comment by l1m0nguy** [comment]
Wow, thanks for the very quick response.
I will check this link, thanks again.
