### ISSUE TITLE
Upstream Source URI

### ISSUE THREAD

**Issue by edrose-tewke** [JeffyCN/meta-rockchip#52]
Are you able to add some comments to the recipe files that indicate where the upstream sources are? Since you've mirrored everything into a single repository, I can't find any way of obtaining the original upstream source URL. Presumably it's only visible on the machine that is updating the mirrors.

Some additional comments for this information would be really helpful.

**Comment by JeffyCN** [comment]
you need to buy rk's sdk to get access to rk's official internal repo

**Comment by JeffyCN** [comment]
that is of cause true for kernel and uboot, and actually they are highlighted not allowed to upload to github...

**Comment by edrose-tewke** [comment]
Who do I have to contact to learn more about the SDK?

And how does this fit in with the GPL? Surely anyone who has paid for the SDK will have to release the Rockchip internal sources the moment they ship a device

**Comment by JeffyCN** [comment]
you can google rk's website to find the mail address.

and i don't think the gpl means people would have to setup a github repo for others to fork the newest version, the company would provide release version for the one who buy the sdk, the newest develop version of code would be in the internal repo.

**Comment by JeffyCN** [comment]
actually rk has 2 kinds of internal repo, one is release version(for customers who buy the sdk), one is develop version(for rk developers).

the release version is much older than develop one, but well tested.

**Comment by JeffyCN** [comment]
and my mirrors are from the internal develop version, might not always up-to-date, i've been warned multiple times not to provide kernel and uboot that newer than the release version

**Comment by JeffyCN** [comment]
FYI, there're other mirrors, for example:
https://github.com/Fruit-Pi
https://gitee.com/caesar-wang/u-boot

**Comment by edrose-tewke** [comment]
Thank you, this is all really good information!
