### ISSUE TITLE
[feature request] Chromium widevine DRM support

### ISSUE THREAD

**Issue by redfast00** [JeffyCN/meta-rockchip#56]
Currently, it's not possible to play DRM protected content (like for example Spotify or Netflix). This is possible on aarch64, see https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/248 and https://aur.archlinux.org/cgit/aur.git/tree/?h=widevine-aarch64. However, this must be enabled while building Chromium (https://github.com/rpmfusion/chromium-freeworld/blob/d2165a468332661df1439208eb930661caaa9f1e/chromium-enable-widevine.patch#L7-L8).

**Comment by JeffyCN** [comment]
i think it would be better to do this in meta-browser
