### ISSUE TITLE
单独构建chromium报错

### ISSUE THREAD

**Issue by iyangsheng** [JeffyCN/meta-rockchip#58]
执行步骤
`
repo init -u https://github.com/JeffyCN/yocto-manifests -b chromium-kirkstone-next
`
`
repo sync
`
`
source ./oe-init-build-env
`
`
bitbake chromium-ozone-wayland
`
错误信息
`
yangsheng@ubuntu:~/build/build$ bitbake chromium-ozone-wayland
Loading cache: 100% |############################################| Time: 0:00:01
Loaded 3731 entries from dependency cache.
Parsing recipes: 100% |##########################################| Time: 0:00:01
Parsing of 2325 .bb files complete (2324 cached, 1 parsed). 3732 targets, 308 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "2.0.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "rockchip-rk3588-evb"
DISTRO               = "poky"
DISTRO_VERSION       = "4.0.8"
TUNE_FEATURES        = "aarch64 armv8a crc"
TARGET_FPU           = ""
meta-oe              
meta-python          = "HEAD:82c75b466e55d7dca7a2364986ecb704cf63d141"
meta-qt5             = "HEAD:aec1934cb2708236c033f2d205d5c3fbbebf7555"
meta-clang           = "HEAD:7e3f2a4126d1bfacda497dfa6b59f3f471f1a984"
meta-rockchip        = "HEAD:0cd3c4d9a1bad3a13be7e80722b44f26e175e0a1"
meta                 
meta-poky            
meta-yocto-bsp       = "HEAD:432bef2a904883fe206b136393d976dc662cb30f"
meta-chromium        = "HEAD:37de9f11f8e7f550c2bad432a092663ea3588d42"

Initialising tasks: 100% |#######################################| Time: 0:00:01
Sstate summary: Wanted 580 Local 2 Mirrors 0 Missed 578 Current 138 (0% match, 19% complete)
NOTE: Executing Tasks
ERROR: chromium-ozone-wayland-110.0.5481.77-r0 do_configure: ExecutionError('/home/yangsheng/build/build/tmp/work/armv8a-poky-linux/chromium-ozone-wayland/110.0.5481.77-r0/temp/run.do_configure.1400', 1, None, None)
ERROR: Logfile of failure stored in: /home/yangsheng/build/build/tmp/work/armv8a-poky-linux/chromium-ozone-wayland/110.0.5481.77-r0/temp/log.do_configure.1400
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/home/yangsheng/build/build/../meta-browser/meta-chromium/recipes-browser/chromium/gn-native_110.0.5481.77.bb:do_populate_sysroot', '/home/yangsheng/build/build/../meta-clang/recipes-devtools/clang/clang-cross_git.bb:do_populate_sysroot', '/home/yangsheng/build/build/../meta-clang/recipes-devtools/clang/compiler-rt_git.bb:do_populate_sysroot', '/home/yangsheng/build/build/../meta-clang/recipes-devtools/clang/libcxx_git.bb:do_populate_sysroot', '/home/yangsheng/build/build/../meta-openembedded/meta-oe/recipes-support/nspr/nspr_4.29.bb:do_populate_sysroot', '/home/yangsheng/build/build/../meta-openembedded/meta-oe/recipes-support/nss/nss_3.74.bb:do_populate_sysroot', '/home/yangsheng/build/build/../meta-rockchip/recipes-graphics/rockchip-libmali/rockchip-libmali.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-bsp/pciutils/pciutils_3.7.0.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-core/expat/expat_2.5.0.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-core/glib-2.0/glib-2.0_2.72.3.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-core/glibc/glibc_2.35.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-core/initscripts/initscripts_1.0.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-core/update-rc.d/update-rc.d_0.8.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-devtools/desktop-file-utils/desktop-file-utils_0.26.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-devtools/qemu/qemu-native_6.2.0.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-devtools/quilt/quilt-native_0.67.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-gnome/gdk-pixbuf/gdk-pixbuf_2.42.10.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-gnome/gtk+/gtk+3_3.24.34.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-gnome/hicolor-icon-theme/hicolor-icon-theme_0.17.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-graphics/cairo/cairo_1.16.0.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-graphics/drm/libdrm_2.4.110.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-graphics/jpeg/libjpeg-turbo_2.1.5.1.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-graphics/mesa/mesa-gl_22.0.3.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-graphics/pango/pango_1.50.4.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-graphics/wayland/wayland_1.20.0.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-graphics/xorg-lib/libxkbcommon_1.4.1.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-multimedia/alsa/alsa-lib_1.2.6.1.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-multimedia/flac/flac_1.3.4.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-multimedia/pulseaudio/pulseaudio_15.0.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-multimedia/webp/libwebp_1.2.4.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-support/atk/at-spi2-atk_2.38.0.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-support/atk/atk_2.38.0.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-support/curl/curl_7.82.0.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-support/libffi/libffi_3.4.4.bb:do_populate_sysroot', '/home/yangsheng/build/build/../poky/meta/recipes-support/libxslt/libxslt_1.1.35.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../meta-openembedded/meta-oe/recipes-devtools/nodejs/nodejs_16.19.0.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../meta-openembedded/meta-oe/recipes-support/nspr/nspr_4.29.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../meta-openembedded/meta-oe/recipes-support/nss/nss_3.74.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../poky/meta/recipes-devtools/bison/bison_3.8.2.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../poky/meta/recipes-devtools/ninja/ninja_1.10.2.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../poky/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../poky/meta/recipes-devtools/python/python3-setuptools_59.5.0.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../poky/meta/recipes-devtools/python/python3_3.10.9.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../poky/meta/recipes-extended/gperf/gperf_3.1.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../poky/meta/recipes-extended/xz/xz_5.2.6.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../poky/meta/recipes-gnome/gtk+/gtk+3_3.24.34.bb:do_populate_sysroot', 'virtual:native:/home/yangsheng/build/build/../poky/meta/recipes-graphics/wayland/wayland_1.20.0.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['gn-native', 'clang-cross-aarch64', 'compiler-rt', 'libcxx', 'nspr', 'nss', 'rockchip-libmali', 'pciutils', 'expat', 'glib-2.0', 'glibc', 'initscripts', 'update-rc.d', 'desktop-file-utils', 'qemu-native', 'quilt-native', 'gdk-pixbuf', 'gtk+3', 'hicolor-icon-theme', 'cairo', 'libdrm', 'libjpeg-turbo', 'mesa-gl', 'pango', 'wayland', 'libxkbcommon', 'alsa-lib', 'flac', 'pulseaudio', 'libwebp', 'at-spi2-atk', 'atk', 'curl', 'libffi', 'libxslt', 'nodejs-native', 'nspr-native', 'nss-native', 'bison-native', 'ninja-native', 'patch-native', 'pkgconfig-native', 'pseudo-native', 'python3-setuptools-native', 'python3-native', 'gperf-native', 'xz-native', 'gtk+3-native', 'wayland-native', 'gcc-runtime', 'zlib', 'flex-native', 'gettext-minimal-native', 'libtool-native', 'texinfo-dummy-native', 'libpciaccess', 'libpthread-stubs', 'libogg', 're2c-native', 'gobject-introspection', 'shared-mime-info', 'libpng', 'libffi-native', 'expat-native', 'libxml2-native', 'linux-libc-headers', 'sqlite3-native', 'zlib-native', 'fribidi', 'fontconfig', 'freetype', 'harfbuzz', 'wayland-protocols', 'libxml2', 'opkg-utils', 'libepoxy', 'libgcc', 'libtirpc-native', 'libnsl2-native', 'ncurses-native', 'gdbm-native', 'openssl-native', 'readline-native', 'bzip2-native', 'util-linux-libuuid-native', 'pixman', 'bash-completion', 'libpcre', 'util-linux', 'kmod', 'python3-installer-native', 'python3-wheel-native', 'dbus', 'at-spi2-core', 'glib-2.0-native', 'openssl', 'libidn2', 'sqlite3', 'binutils-cross-aarch64', 'clang-native', 'sbc', 'ofono', 'libcap', 'shadow', 'speexdsp', 'libatomic-ops', 'avahi', 'libsndfile1', 'eudev', 'bluez5', 'shadow-native', 'base-passwd', 'libtool', 'shadow-sysroot', 'base-files', 'brotli-native', 'c-ares-native', 'icu-native', 'pango-native', 'gobject-introspection-native', 'libxi-native', 'cairo-native', 'libxrender-native', 'libxcursor-native', 'libxdamage-native', 'fontconfig-native', 'atk-native', 'libxfixes-native', 'libxext-native', 'libpng-native', 'libx11-native', 'at-spi2-atk-native', 'libjpeg-turbo-native', 'libxrandr-native', 'libxcomposite-native', 'gdk-pixbuf-native', 'compiler-rt-native', 'libcxx-native', 'attr-native', 'm4-native', 'util-macros', 'autoconf-archive', 'python3', 'cmake-native', 'icu', 'perl-native', 'bzip2', 'ncurses', 'libcap-ng', 'util-linux-libuuid', 'libxcrypt', 'xz', 'unzip-native', 'python3-flit-core-native', 'gettext-native', 'util-linux-native', 'libpcre-native', 'libunistring', 'gnu-config-native', 'binutils-native', 'libedit-native', 'swig-native', 'mobile-broadband-provider-info', 'ell', 'attr', 'libdaemon', 'libvorbis', 'readline', 'libical', 'libxft-native', 'fribidi-native', 'freetype-native', 'harfbuzz-native', 'xorgproto-native', 'util-macros-native', 'libxcb-native', 'libsm-native', 'pixman-native', 'xtrans-native', 'at-spi2-core-native', 'dbus-native', 'shared-mime-info-native', 'gdbm', 'libnsl2', 'libtirpc', 'curl-native', 'zstd-native', 'make-native', 'libpcre2-native', 'libcap-ng-native', 'elfutils-native', 'vala', 'libxau-native', 'xcb-proto-native', 'libxdmcp-native', 'libpthread-stubs-native', 'libice-native', 'libxtst-native', 'itstool-native', 'libarchive-native', 'libmicrohttpd-native', 'lzo-native', 'libgcrypt-native', 'gnutls-native', 'libgpg-error-native', 'libcap-native', 'libunistring-native', 'libidn2-native', 'nettle-native', 'gmp-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| ERROR at //build/config/linux/dri/BUILD.gn:11:20: Script returned non-zero exit code.
|   dri_driver_dir = exec_script(pkg_config_script,
|                    ^----------
| Current dir: /home/yangsheng/build/build/tmp/work/armv8a-poky-linux/chromium-ozone-wayland/110.0.5481.77-r0/chromium-110.0.5481.77/out/Release/
| Command: python3 /home/yangsheng/build/build/tmp/work/armv8a-poky-linux/chromium-ozone-wayland/110.0.5481.77-r0/chromium-110.0.5481.77/build/config/linux/pkg-config.py --dridriverdir dri
| Returned 1 and printed out:
| 
| Error from pkg-config.
| 
| stderr:
| 
| Package dri was not found in the pkg-config search path.
| Perhaps you should add the directory containing `dri.pc'
| to the PKG_CONFIG_PATH environment variable
| No package 'dri' found
| 
| See //content/gpu/BUILD.gn:142:18: which caused the file to be included.
|     configs += [ "//build/config/linux/dri" ]
|                  ^-------------------------
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/yangsheng/build/build/../meta-browser/meta-chromium/recipes-browser/chromium/chromium-ozone-wayland_110.0.5481.77.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2603 tasks of which 647 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/yangsheng/build/build/../meta-browser/meta-chromium/recipes-browser/chromium/chromium-ozone-wayland_110.0.5481.77.bb:do_configure
Summary: There was 1 WARNING message.
Summary: There was 1 ERROR message, returning a non-zero exit code.
`

**Comment by iyangsheng** [comment]
> 尚不支持 r110，请尝试将元浏览器回滚到 r109

回滚到109后构建成功，在build/tmp/deploy/rpm/armv8a/目录下生成了rpm格式的安装包，如何在ubuntu系统中安装
![image](https://user-images.githubusercontent.com/39045336/225793517-ea3d49e2-2f6f-4cd0-a876-3c1c7da80c2d.png)

**Comment by JeffyCN** [comment]
this repo is for yocto only, not for ubuntu. and it's dangerous to install packages acrossing systems.

if you really want to do so, please make sure that:
1/ the yocto's glibc should not be newer than the ubuntu's
2/ unpack the yocto's chromium package into ubuntu manually
3/ if the chromium complains about depended libraries mismatching when running, find those libraries in yocto and put them into ubuntu's /usr/lib/chromium/ manually

**Comment by iyangsheng** [comment]
thanks

**Comment by JeffyCN** [comment]
r110 should be supported now.
