### ISSUE TITLE
kernel 5.10 build fails

### ISSUE THREAD

**Issue by ballestrerod** [JeffyCN/meta-rockchip#66]
hi,
i'm trying to build core-image-minimal for rk3328-evb board but kernel build fails. maybe a patch is missing.

Log data follows:                                                                                                                                                                                           
| DEBUG: Executing shell function do_compile_kernelmodules                                                                                                                                                  
| NOTE: KBUILD_BUILD_TIMESTAMP: Sat Jan  8 10:24:03 UTC 2022                                                                                                                                                
| NOTE: make CC=aarch64-poky-linux-gcc   -fuse-ld=bfd -fmacro-prefix-map=/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work/rockchip_rk3328_evb-poky-linux/linux-rockchip/5.10-
r0=/usr/src/debug/linux-rockchip/5.10-r0                      -fdebug-prefix-map=/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work/rockchip_rk3328_evb-poky-linux/linux-rockch
ip/5.10-r0=/usr/src/debug/linux-rockchip/5.10-r0                      -fdebug-prefix-map=/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work/rockchip_rk3328_evb-poky-linux/linu
x-rockchip/5.10-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work/rockchip_rk3328_evb-poky-linux/linux-rockchip/5.1
0-r0/recipe-sysroot-native=  -fdebug-prefix-map=/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source=/usr/src/kernel -fdebug-prefix-map=
/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-build-artifacts=/usr/src/kernel  --sysroot=/home/ballest/rockhevc_workspace/oses/rockhevc-
kirkstone/build_evk3328/tmp/work/rockchip_rk3328_evb-poky-linux/linux-rockchip/5.10-r0/recipe-sysroot LD=aarch64-poky-linux-ld.bfd    --sysroot=/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/bui
ld_evk3328/tmp/work/rockchip_rk3328_evb-poky-linux/linux-rockchip/5.10-r0/recipe-sysroot HOSTCC=gcc  HOSTCFLAGS=-isystem/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work/rock
chip_rk3328_evb-poky-linux/linux-rockchip/5.10-r0/recipe-sysroot-native/usr/include -O2 -pipe HOSTLDFLAGS=-L/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work/rockchip_rk3328_
evb-poky-linux/linux-rockchip/5.10-r0/recipe-sysroot-native/usr/lib                         -L/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work/rockchip_rk3328_evb-poky-linux
/linux-rockchip/5.10-r0/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3
328/tmp/work/rockchip_rk3328_evb-poky-linux/linux-rockchip/5.10-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3
328/tmp/work/rockchip_rk3328_evb-poky-linux/linux-rockchip/5.10-r0/recipe-sysroot-native/lib                         -Wl,-rpath,/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/w
ork/rockchip_rk3328_evb-poky-linux/linux-rockchip/5.10-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work/r
ockchip_rk3328_evb-poky-linux/linux-rockchip/5.10-r0/recipe-sysroot-native/lib                         -Wl,-O1 -Wl,--allow-shlib-undefined -Wl,--dynamic-linker=/home/ballest/rockhevc_workspace/oses/rockhe
vc-kirkstone/build_evk3328/tmp/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2 HOSTCPP=gcc  -E HOSTCXX=g++  HOSTCXXFLAGS=-isystem/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk
3328/tmp/work/rockchip_rk3328_evb-poky-linux/linux-rockchip/5.10-r0/recipe-sysroot-native/usr/include -O2 -pipe PAHOLE=false -C /home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/w
ork/rockchip_rk3328_evb-poky-linux/linux-rockchip/5.10-r0/linux-rockchip_rk3328_evb-standard-build -j 8 modules
| make: Entering directory '/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work/rockchip_rk3328_evb-poky-linux/linux-rockchip/5.10-r0/linux-rockchip_rk3328_evb-standard-build'
|   GEN     Makefile                          
|   CALL    /home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source/scripts/atomic/check-atomics.sh
|   CALL    /home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source/scripts/checksyscalls.sh
|   CC [M]  drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/aiutils.o
| /home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source/drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/aiutils.c:25:10: fatal error: ty
pedefs.h: No such file or directory              
|    25 | #include <typedefs.h>
|       |          ^~~~~~~~~~~~                                                                       
| compilation terminated.                                                                             
| make[7]: *** [/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source/scripts/Makefile.build:273: drivers/net/wireless/rockchip_wlan/rkwi
fi/bcmdhd/aiutils.o] Error 1                   
| make[6]: *** [/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source/scripts/Makefile.build:516: drivers/net/wireless/rockchip_wlan/rkwi
fi/bcmdhd] Error 2                   
| make[5]: *** [/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source/scripts/Makefile.build:516: drivers/net/wireless/rockchip_wlan/rkwi
fi] Error 2        
| make[4]: *** [/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source/scripts/Makefile.build:516: drivers/net/wireless/rockchip_wlan] Err
or 2                   
| make[3]: *** [/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source/scripts/Makefile.build:516: drivers/net/wireless] Error 2
| make[2]: *** [/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source/scripts/Makefile.build:516: drivers/net] Error 2
| make[1]: *** [/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source/Makefile:1915: drivers] Error 2
| make[1]: *** Waiting for unfinished jobs....
| make: *** [/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work-shared/rockchip-rk3328-evb/kernel-source/Makefile:185: __sub-make] Error 2
| make: Leaving directory '/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/build_evk3328/tmp/work/rockchip_rk3328_evb-poky-linux/linux-rockchip/5.10-r0/linux-rockchip_rk3328_evb-standard-build'
| ERROR: oe_runmake failed           
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/ballest/rockhevc_workspace/oses/rockhevc-kirkstone/sources/meta-rockchip/recipes-kernel/linux/linux-rockchip_5.10.bb:do_compile_kernelmodules) failed with exit code '1'

**Comment by JeffyCN** [comment]
check:
https://github.com/JeffyCN/meta-rockchip/issues/65#issuecomment-1545715303

maybe i can try to find a way to only apply that patch for github kernel
