### ISSUE TITLE
TINKER BOARD R2.0 not booting

### ISSUE THREAD

**Issue by chrisiberg** [JeffyCN/meta-rockchip#69]
I did a complete clean install and used "rockchip-rk3288-evb" with "core-image-minimal"

Can you please help me to get it run?

Relocation Offset: 00000000
Relocation fdt: 7bcab950 - 7bcacde5
CR: M/C/I
Using default environment

DM: v1
no mmc device at slot 1
Found IDB in SDcard
dwmmc@ff0c0000: 1 (SD), dwmmc@ff0f0000: 0
Bootdev(atags): mmc 1
MMC1: Legacy, 52Mhz
PartType: EFI
No misc partition
boot mode: None
RESC: 'boot', blk@0x0000b580
optee api revision: 2.0
TEEC: Waring: Could not find security partition
ERR [0x0] TEE-CORE:open_tee_file:1452: Can not open meta file
INF [0x0] TEE-CORE:ree_fs_open:1510: Warning! meta file exist but open fail! try to recreate!
ERR [0x0] TEE-CORE:encrypt_and_write_file:729: bytes(0) != ciphertext size(176)
ERR [0x0] TEE-CORE:create_tee_file:1431: Failed to create new meta file
ERR [0x0] TEE-CORE:ree_fs_open:1516: Failed to open TEE file
ERR [0x0] TEE-CORE:open_tee_file:1452: Can not open meta file
INF [0x0] TEE-CORE:ree_fs_open:1510: Warning! meta file exist but open fail! try to recreate!
ERR [0x0] TEE-CORE:encrypt_and_write_file:729: bytes(0) != ciphertext size(176)
ERR [0x0] TEE-CORE:create_tee_file:1431: Failed to create new meta file
ERR [0x0] TEE-CORE:ree_fs_open:1516: Failed to open TEE file
/home/chris/yocto/poky2/build/tmp/work/rockchip_rk3288_evb-poky-linux-gnueabi/u-boot-rockchip/1_2017.09-r0/git/lib/avb/libavb_user/avb_ops_user.c: init lock state error
Error determining whether device is unlocked.
Device is: UNLOCKED
DTB: rk-kernel.dtb
HASH(c): OK
I2c0 speed: 400000Hz
PMIC:  RK808
vdd_arm 1100000 uV
vdd_gpu 1100000 uV
vcc_log 1100000 uV
voltage(0 uV) is invalid from SWITCH_REG2
io-domain: OK
Could not find baseparameter partition
Rockchip UBOOT DRM driver version: v1.0.1
xfer: num: 2, addr: 0x50
xfer: num: 2, addr: 0x50
Monitor has basic audio support
Could not find baseparameter partition
mode:1280x720
hdmi@ff980000:  detailed mode clock 74250 kHz, flags[5]
    H: 1280 1390 1430 1650
    V: 0720 0725 0730 0750
bus_format: 100a
CEA mode used vic=4
final pixclk = 74250000 tmdsclk = 74250000
PHY powered down in 0 iterations
PHY PLL locked 1 iterations
PHY powered down in 1 iterations
PHY PLL locked 1 iterations
sink has audio support
hdmi_set_clk_regenerator: fs=48000Hz ftdms=74.250MHz N=6144 cts=74250
DDR Version 1.11 20210818
In
Channel a: LPDDR3 400MHz
MR0=0x58
MR1=0x58
MR2=0x58
MR3=0x58
MR4=0x2
MR5=0x1
MR6=0x16
MR7=0x0
MR8=0x1F
MR9=0x1F
MR10=0x1F
MR11=0x1F
MR12=0x1F
MR13=0x1F
MR14=0x1F
MR15=0x1F
MR16=0x1F
Bus Width=32 Col=10 Bank=8 Row=15 CS=1 Die Bus-Width=32 Size=1024MB
Channel b: LPDDR3 400MHz
MR0=0x58
MR1=0x58
MR2=0x58
MR3=0x58
MR4=0x2
MR5=0x1
MR6=0x16
MR7=0x0
MR8=0x1F
MR9=0x1F
MR10=0x1F
MR11=0x1F
MR12=0x1F
MR13=0x1F
MR14=0x1F
MR15=0x1F
MR16=0x1F
Bus Width=32 Col=10 Bank=8 Row=15 CS=1 Die Bus-Width=32 Size=1024MB
Memory OK
Memory OK
OUT
Boot1 Release Time: Jul 22 2021 09:08:57, version: 2.63
ChipType = 0x8, 250
mmc2:cmd1,20
emmc reinit
mmc2:cmd1,20
emmc reinit
mmc2:cmd1,20
SdmmcInit=2 1
mmc0:cmd5,20
SdmmcInit=0 0
BootCapSize=0
UserCapSize=30424MB
FwPartOffset=2000 , 0
StorageInit ok = 25771
SecureMode = 0
SecureInit read PBA: 0x4
SecureInit read PBA: 0x404
SecureInit read PBA: 0x804
SecureInit read PBA: 0xc04
SecureInit read PBA: 0x1004
SecureInit read PBA: 0x1404
SecureInit read PBA: 0x1804
SecureInit read PBA: 0x1c04
SecureInit ret = 0, SecureMode = 0
atags_set_bootdev: ret:(0)
GPT part:  0, name:            uboot, start:0x4000, size:0x2000
GPT part:  1, name:            trust, start:0x6000, size:0x2000
GPT part:  2, name:             boot, start:0x8000, size:0x3670
GPT part:  3, name:           rootfs, start:0xc000, size:0xa240
find part:uboot OK. first_lba:0x4000.
find part:trust OK. first_lba:0x6000.
LOADER Check OK! 0x4000, 176166
TOS    Check OK! 0x6000, 265707
Enter Trust OS
INF [0x0] TEE-CORE:init_primary_helper:385: Core0 Initializing (1.1.0-432-gc99a453d #4 Mon Aug 17 09:16:49 UTC 2020 arm)

INF [0x0] TEE-CORE:init_primary_helper:386: Release version: 1.3

INF [0x0] TEE-CORE:init_primary_helper:387: Next entry point address: 0x200000

INF [0x0] TEE-CORE:init_teecore:83: teecore inits done

U-Boot 2017.09 (Apr 03 2023 - 06:43:01 +0000)

Model: Evb-RK3288
PreSerial: 2, raw, 0xff690000
DRAM:  2 GiB
Sysmem: init
Relocation Offset: 00000000
Relocation fdt: 7bcab950 - 7bcacde5
CR: M/C/I
Using default environment

DM: v1
no mmc device at slot 1
Found IDB in SDcard
dwmmc@ff0c0000: 1 (SD), dwmmc@ff0f0000: 0
Bootdev(atags): mmc 1
MMC1: Legacy, 52Mhz
PartType: EFI
No misc partition
boot mode: None
RESC: 'boot', blk@0x0000b580
optee api revision: 2.0
TEEC: Waring: Could not find security partition
ERR [0x0] TEE-CORE:open_tee_file:1452: Can not open meta file
INF [0x0] TEE-CORE:ree_fs_open:1510: Warning! meta file exist but open fail! try to recreate!
ERR [0x0] TEE-CORE:encrypt_and_write_file:729: bytes(0) != ciphertext size(176)
ERR [0x0] TEE-CORE:create_tee_file:1431: Failed to create new meta file
ERR [0x0] TEE-CORE:ree_fs_open:1516: Failed to open TEE file
ERR [0x0] TEE-CORE:open_tee_file:1452: Can not open meta file
INF [0x0] TEE-CORE:ree_fs_open:1510: Warning! meta file exist but open fail! try to recreate!
ERR [0x0] TEE-CORE:encrypt_and_write_file:729: bytes(0) != ciphertext size(176)
ERR [0x0] TEE-CORE:create_tee_file:1431: Failed to create new meta file
ERR [0x0] TEE-CORE:ree_fs_open:1516: Failed to open TEE file
/home/chris/yocto/poky2/build/tmp/work/rockchip_rk3288_evb-poky-linux-gnueabi/u-boot-rockchip/1_2017.09-r0/git/lib/avb/libavb_user/avb_ops_user.c: init lock state error
Error determining whether device is unlocked.
Device is: UNLOCKED
DTB: rk-kernel.dtb
HASH(c): OK
I2c0 speed: 400000Hz
PMIC:  RK808
vdd_arm 1100000 uV
vdd_gpu 1100000 uV
vcc_log 1100000 uV
voltage(0 uV) is invalid from SWITCH_REG2
io-domain: OK
Could not find baseparameter partition
Rockchip UBOOT DRM driver version: v1.0.1
xfer: num: 2, addr: 0x50
xfer: num: 2, addr: 0x50
Monitor has basic audio support
Could not find baseparameter partition
mode:1280x720
hdmi@ff980000:  detailed mode clock 74250 kHz, flags[5]
    H: 1280 1390 1430 1650
    V: 0720 0725 0730 0750
bus_format: 100a
CEA mode used vic=4
final pixclk = 74250000 tmdsclk = 74250000
PHY powered down in 0 iterations
PHY PLL locked 1 iterations
PHY powered down in 1 iterations
PHY PLL locked 1 iterations
sink has audio support
hdmi_set_clk_regenerator: fs=48000Hz ftdms=74.250MHz N=6144 cts=74250

**Comment by JeffyCN** [comment]
that config is for evb board, not "tinker board".

you may need their support to get the correct u-boot/kernel code and config firstly, then follow the "supporting new machine" section in:
https://github.com/JeffyCN/meta-rockchip



or you can use the generated rootfs.img alone:
flash the original bootable firmware, then flash the rootfs.img generated from this layer
