### ISSUE TITLE
DTS for ioT-3288A

### ISSUE THREAD

**Issue by chrisiberg** [JeffyCN/meta-rockchip#70]
Does anybody know whicht devicetree (dts) would fit this board?

https://fccid.io/2AITM-IOT-3288A/Label/Product-Label-3941787

TISMART
ioT-3288A
REV:2.0
2021-05-08

**Comment by chrisiberg** [comment]
The manufacturer http://www.smdt.com.cn/ answers that the iot-3288 doesn’t support linux.
Can there be any hardware related differences?
When android is running I can't imagine that linux can't, ore I'm wrong?

**Comment by JeffyCN** [comment]
i don't know that board, but i think it should support linux.

but you may need to get source code of it's loader and kernel
