### ISSUE TITLE
Remove flags for is_official_build=false in chromium bbappend as it causes a debug breakpoint with touchscreens

### ISSUE THREAD

**Issue by medemi68** [JeffyCN/meta-rockchip#77]
Good Evening,

I recently discovered an issue that had me researching for days (it turned out to be a very easy fix). Basically I am using a USB touchscreen (ILITEK based) with a rockchip RK3288 based board and I have chromium-x11 built for that machine.

When using the touchscreen after launching chromium from a command line, chromium immediately closes after touching the screen with a fatal error relating to something to do with touch_factory_x11.cc. (See [here](https://chromium.googlesource.com/chromium/src/+/refs/tags/111.0.5563.54/ui/events/devices/x11/touch_factory_x11.cc) on line 279) don't know why this error occurs or if it is a bug or something that is triggering the error, although the closing of chromium is most certainly related to chromium being built in debug mode (you need to have is_debug=false and is_official_build=true for it to not be in debug mode, as is the default in meta-browser/meta-chromium). 

Either way, removing is_official_build=false and is_debug=false from the GN_ARGS:append in the chromium.bbappend file fixes the issue. I hope this is helpful to someone else even if it does not get approved, but I do think that these should be removed from here as you'd probably want to be building a release build anyway.

Of course I can only assume these flags are probably there to aid in development of this layer. Is there a more suitable option? Perhaps we could write this in the documentation? I am relatively new to Yocto so I don't know if you can remove args from an append through another layer if it is at all possible.

**Comment by JeffyCN** [comment]
it's okay to remove that, but that fatal error would surely a chromium issue
