### ISSUE TITLE
Modifying boot logos on RK3288

### ISSUE THREAD

**Issue by medemi68** [JeffyCN/meta-rockchip#78]
Hi everyone,

Once again I just wanted to share something that could be helpful to someone else that might not be immediately obvious / might require some researching.

I was trying to modify the boot logos for an RK3288 based board and I ended up searching through the source code of the mirror for u-boot in https://github.com/JeffyCN/mirrors/tree/u-boot, going through a complete rabbithole where I even found the the calling function for displaying the bmp files.

Long story short, if you want to modify the logos, they are in the linux-rockchip kernel source tree at https://github.com/JeffyCN/mirrors/tree/kernel-4.4, right in the root directory (you'll see them called logo.bmp and logo_kernel.bmp). So you'll need to write a patch (which can be easily done using Yocto's devtool) in order to replace those files before they are being built by yocto's build system.

If you go down the rabbithole I went through, you'll also learn that they get compiled into the boot.img file at the end which you simply can't just easily extract and repackage to change as it uses a proprietary filesystem format from Rockchip. 

Hope this gets added to documentation or something to help someone else!

**Comment by JeffyCN** [comment]
Well, there's a document for that in Rockchip's official SDK(under docs/), i used to mirror it here, but due to company policy, i'm not allowed to provide it anymore :(
