### ISSUE TITLE
Running bitbake -c clean deletes rkbin

### ISSUE THREAD

**Issue by medemi68** [JeffyCN/meta-rockchip#81]
Hi,

I've noticed that running `bitbake -c clean u-boot-rockchip` deletes the rkbin stuff that is in that folder, requiring you to actually run `bitbake -c cleanall u-boot-rockchip` forcing a redownload. Considering that u-boot-rockchip is quite large, is this the intended behaviour?

Perhaps you could write a custom clean command to leave the rkbin intact?

Miguel

**Comment by JeffyCN** [comment]
please check the readme for using a local custom u-boot
