### ISSUE TITLE
Build gnome desktop base on x11

### ISSUE THREAD

**Issue by ccupla** [JeffyCN/meta-rockchip#84]
Hi，I tried adding packagegroup-gnome-desktop on top of core-image-minimal-xfce.bb，but mutter always depends on wayland.
Even if I remove the wayland depends from mutter, the build image still fails to start the gnome-xorg session.
Can you provide some repices for reference？thanks.

Machine: rockchip-rk3588-evb
Branch: kirkstone

@JeffyCN

**Comment by JeffyCN** [comment]
sorry, i don't know much about that.

It looks like the wayland is hard coded in meta-oe's mutter .bb.
maybe open issue in: https://github.com/openembedded/meta-openembedded/issues
