### ISSUE TITLE
Rock3 Model C, build settings

### ISSUE THREAD

**Issue by ozkansen** [JeffyCN/meta-rockchip#96]
Hi,
Which machine settings should I use on yocto for model "Rock3 Model C" ?

Thanks.

Ref: https://wiki.radxa.com/Rock3/3c

**Comment by JeffyCN** [comment]
sorry, this layer only support a few rockchip evb boards.

please check the readme.md for more details.

**Comment by chrisiberg** [comment]
You have to get the devicetree for this board, look here.
https://github.com/radxa/kernel/tree/stable-4.19-rock3/arch/arm64/boot/dts/rockchip

**Comment by JeffyCN** [comment]
https://github.com/JeffyCN/meta-rockchip/blob/941f4102d94c8943bcbd6a12257605316fba7638/README.md#v-supporting-new-machine

**Comment by chrisiberg** [comment]
@JeffyCN just wanted to give ozkansen a hint 😉

**Comment by ozkansen** [comment]
thanks, I have no idea how to do it but I will try :)

**Comment by JeffyCN** [comment]
one simple way is to keep your original working kernel and loader, and replace the rootfs image only(might need to install gpu lib(and maybe firmware too) and wifi/bt modules/firmware manually).
