### ISSUE TITLE
bitbake core-image-minimal returns errors with Machine = "rockchip-rk3326-evb"

### ISSUE THREAD

**Issue by xiaotiansf** [JeffyCN/meta-rockchip#99]
Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-linux.dtsi:114.1-5 Label or path rng not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-linux.dtsi:118.1-11 Label or path video_phy not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:184.1-10 Label or path bus_apll not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:189.1-9 Label or path cif_new not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:330.1-13 Label or path dsi_in_vopl not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:339.1-5 Label or path dfi not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:343.1-5 Label or path dmc not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:786.1-9 Label or path isp_mmu not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:790.1-15 Label or path mipi_dphy_rx0 not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:822.1-8 Label or path nandc0 not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:826.1-8 Label or path rkisp1 not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:851.1-8 Label or path rk_rga not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:855.1-18 Label or path rockchip_suspend not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:925.1-9 Label or path vip_mmu not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:937.1-6 Label or path vopl not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:941.1-10 Label or path vopl_mmu not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:945.1-9 Label or path mpp_srv not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:949.1-6 Label or path vdpu not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:953.1-6 Label or path vepu not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:957.1-9 Label or path vpu_mmu not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:961.1-6 Label or path hevc not found
| Error: /home/xiaos/canvia/yocto/build/tmp/work-shared/rockchip-rk3326-evb/kernel-source/arch/arm64/boot/dts/rockchip/rk3326-evb-lp3-v10-linux.dts:965.1-10 Label or path hevc_mmu not foun

with:
# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/xiaos/canvia/yocto/meta-rockchip \
  /home/xiaos/canvia/yocto/poky/meta \
  /home/xiaos/canvia/yocto/poky/meta-poky \
  /home/xiaos/canvia/yocto/poky/meta-yocto-bsp \
  /home/xiaos/canvia/yocto/meta-openembedded/meta-oe \

Any idea how to fix the build errors?

**Comment by JeffyCN** [comment]
sorry, that kernel might be out-dated, and i'm not allowed to update it.

you can follow the guide in readme.md to use your local kernel source for your board.
